// Generated by gencpp from file vision_tracking/Position.msg
// DO NOT EDIT!


#ifndef VISION_TRACKING_MESSAGE_POSITION_H
#define VISION_TRACKING_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_tracking
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : position_x(0)
    , position_y(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : position_x(0)
    , position_y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _position_x_type;
  _position_x_type position_x;

   typedef uint16_t _position_y_type;
  _position_y_type position_y;





  typedef boost::shared_ptr< ::vision_tracking::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_tracking::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::vision_tracking::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::vision_tracking::Position > PositionPtr;
typedef boost::shared_ptr< ::vision_tracking::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_tracking::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_tracking::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_tracking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vision_tracking': ['/home/pi/ROS-Feature-Tracking/src/vision_tracking/msg'], 'std_msgs': ['/home/pi/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_tracking::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_tracking::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_tracking::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_tracking::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_tracking::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_tracking::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_tracking::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69cb99f109ace36b4ffea89389ff8940";
  }

  static const char* value(const ::vision_tracking::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69cb99f109ace36bULL;
  static const uint64_t static_value2 = 0x4ffea89389ff8940ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_tracking::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_tracking/Position";
  }

  static const char* value(const ::vision_tracking::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_tracking::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 position_x\n"
"uint16 position_y\n"
;
  }

  static const char* value(const ::vision_tracking::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_tracking::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_x);
      stream.next(m.position_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_tracking::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_tracking::Position_<ContainerAllocator>& v)
  {
    s << indent << "position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_TRACKING_MESSAGE_POSITION_H
